name: fritter_for_reddit
description: An unofficial Reddit client written in Flutter.

version: 0.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  cached_network_image: ^2.1.0+1
  draw: ^0.9.1
  extended_image: ^0.7.2
  flutter_custom_tabs: ^0.6.0
  flutter_html: ^0.11.1
  flutter_secure_storage: ^3.3.2
  http: ^0.12.0+4
  intl: ^0.16.1
  meta: ^1.1.8
  html_unescape: ^1.0.1+3
  palette_generator: ^0.2.2
  photo_view: ^0.9.2
  provider: ^4.0.5
  shared_preferences: ^0.5.6+3
  video_player:
  webview_flutter: ^0.3.19+9
  image_downloader: ^0.19.2
  video_provider: ^1.2.3+1
  flutter_cache_manager: ^1.2.0
  conditional_wrapper: ^1.0.1
  flutter_markdown: ^0.3.4
  rxdart: ^0.23.1
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  hive: ^1.4.1+1
  sticky_headers: ^0.1.8+1
  conditional_builder: ^1.0.2
  link_previewer: ^1.2.1
  get_it: ^4.0.1
  url_launcher: ^5.4.2
  flutter_gifimage:
    git:
      url: https://github.com/ThinkDigitalSoftware/flutter_gifimage.git
  flutter_pagewise: ^1.2.3
  animated_layout:
    git:
      url: https://github.com/ThinkDigitalSoftware/animated_layout.git
  skeleton_text: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1

dependency_overrides:
  http: ^0.12.0+4

flutter:
  uses-material-design: true

  assets:
    - assets/